# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Gamedev Fyi Theme"
license = "MIT"
licenselink = "https://gitlab.com/gamedev-fyi/gamedev-fyi-theme/blob/master/LICENSE.md"
description = "This is the base theme for the GameDev FYI Pages."
homepage = "https://gitlab.com/gamedev-fyi/gamedev-fyi-theme"
tags = []
features = []
min_version = "0.20"

[author]
  name = "Goose Ninja"
  homepage = "https://goose.ninja"
